### ISSUE TITLE
Problem with scenarios with a lot of nodes ? 

### ISSUE THREAD

**Issue by EliseuFelipe** [signetlabdei/millicar#10]
Hi,

I'm trying to simulate a scenario with a high number of nodes but I got this message when I try to pair the devices :
"aborted. cond="devices.GetN () > m_phyMacConfig->GetSlotsPerSubframe ()", msg="Too many devices", file=../src/millicar/helper/mmwave-vehicular-helper.cc, line=321 terminate called without an active exception"

Looks like by default each device uses a slot and thereby I just can use few nodes ( I think its 8 slots, so 8 nodes) . Is it possible to allow more devices ? I did read the millicar paper and its said something about the SetSfAllocationInfo method but its not clear. 

Thank you.

**Comment by tommasozugno** [comment]
Yes, but you should change how the slots are assigned to the users (see the methods MmWaveSidelinkMac::DoSlotIndication () and MmWaveSidelinkMac::ScheduleResources ())

**Comment by EliseuFelipe** [comment]
Hi @tommasozugno, 

The method "SetSfAllocationInfo()" receives a pattern that is created in "CreateSchedulingPattern()". But in the method "CreateSchedulingPattern()" there is a to do "// TODO implement scheduling pattern that support groups with a number of vehicle greater than the number of slots per subframe".

I would like to know if I can only by configuration use a group with a number of vehicles greater than the number of slots using the current version of MILLICAR without me implementing code [in the MILLICAR source code]. 

Thank you again.

**Comment by tommasozugno** [comment]
No, you should modify the code to achieve this behavior

**Comment by BrenoMelo** [comment]
@EliseuFelipe have you solved/modified the code? I am facing the same problem and I have no clue how to solve it.
