### ISSUE TITLE
Does millicar module compatible for NR sub-6GHz frequency?

### ISSUE THREAD

**Issue by kaitofah** [signetlabdei/millicar#11]
Hi millicar team,

I really interested in your module and I wonder if I'd to implement on sub-6GHz band, is it still working ? or I just change SCS.

Thank you in adv.
faa

**Comment by kaitofah** [comment]
I would to send the data with groupcast communication for platooning, Could you please suggest how to configure it ? 
is there some example? 

Thanks

**Comment by MatteoDrago** [comment]
Hi @kaitofah, the implemented channel model supports also working at sub-6 GHz. However, please refer to the standard's documents to check if any operation at the PHY of MAC layers should be different from what has been implemented in this version of the module.

Regarding groupcast communication, we have not implemented it yet.

**Comment by kaitofah** [comment]
Thank you very much for your kind support @MatteoDrago

**Comment by kaitofah** [comment]
@MatteoDrago 
May I ask more question? If I want to add RAN (gNB or eNB), which function that I can modified or use it?

**Comment by MatteoDrago** [comment]
You can use MilliCar together with the ns3-mmwave module

**Comment by kaitofah** [comment]
@MatteoDrago Thank you very much
