### ISSUE TITLE
Issues about reproducing the simulations of paper MilliCar

### ISSUE THREAD

**Issue by hanghoo** [signetlabdei/millicar#12]
Hi Tommaso,

I am reading your paper "MilliCar - An ns-3 Module for mmWave NR V2X Networks" and want to obtain some results in your paper, like the latency and throughput.

Nevertheless, I cannot get the correct average latency. May I ask how to set up the source rate?

I am looking forward to your response. Thank you very much!

**Comment by tommasozugno** [comment]
The latency plot in that paper is obtained with the example vehicular-simple-one.cc. To set up the source rate you need to change the value of the variable interPacketInterval. The example generates a trace file called simple-one-stats.txt in which each line corresponds to a received packet. The first and the last column corresponds to the time instant at which the packet was received and transmitted, respectively. From those values you can compute the e2e latency.

**Comment by hanghoo** [comment]
> The latency plot in that paper is obtained with the example vehicular-simple-one.cc. To set up the source rate you need to change the value of the variable interPacketInterval. The example generates a trace file called simple-one-stats.txt in which each line corresponds to a received packet. The first and the last column corresponds to the time instant at which the packet was received and transmitted, respectively. From those values you can compute the e2e latency.

Thank you for your quick response.

**Comment by hanghoo** [comment]
Thank you for your prompt response. Your answer is very helpful.

**Comment by hanghoo** [comment]
Hi Tommaso @tommasozugno,

May I consult you on how I can calculate the delay at the different layers of the protocol stack? 
Currently, my preliminary idea is to insert a timer in each layer and calculate the duration between each layer receiving a package and sending the package. How do you think of it?

Thank you very much!
