### ISSUE TITLE
How to change the vehicle transmission distance?

### ISSUE THREAD

**Issue by ntuxtj** [signetlabdei/millicar#18]
Hello, I'm doing an experiment on the Internet of Vehicles recently. I really want to know how to change the vehicle propagation distance, which is very important for my topic. I have also searched for some materials, but haven't found a reliable method yet. Can you teach me if it is convenient for you?

**Comment by MatteoDrago** [comment]
Hi, 

In order to change vehicles propagation distance, it is sufficient to increase the distance among nodes in the simulation script. Nodes reciprocal distance is automatically retrieved when evaluating propagation effects.  

Best
