### ISSUE TITLE
performance evaluation of millcar

### ISSUE THREAD

**Issue by obifranky** [signetlabdei/millicar#4]
Greetings, 
please i am trying to get the performance evaluation of millcar for v2v, using the 4  v2v scenarios. i have done the simulation, but the files generated  e.g (group1.txt, scenario.txt, user1.txt  etc) has  alot of numbers without label, so it is difficult to calculate a dn plot the throughput, latency, PRR for scenario 2 and 4 especially at different parameters considering the NLOS interference evaluation.
please i need help or an idea that can help me carry out an optimal performance evaluation for v2v at mmwave using millicar.

**Comment by tommasozugno** [comment]
Hi, 
You just need to have a look at the simulation script and check the definition of the callbacks used to generate the files. For example, in vehicular-simple-four.cc, the files user_1.txt and user_2.txt are generated by the [Rx callback](https://github.com/signetlabdei/millicar/blob/eb1d8bb807718815441f7c1d6dea9336b0b5dcf9/examples/vehicular-simple-four.cc#L45), which prints the following information: `time, packet-size, sequence-number, delay `(as you can see [here](https://github.com/signetlabdei/millicar/blob/eb1d8bb807718815441f7c1d6dea9336b0b5dcf9/examples/vehicular-simple-four.cc#L51))

**Comment by obifranky** [comment]
thanks for the kind reply. yes i saw the callback definition, but i have a problem 
scenario 1 generated sinr-mcs.txt was not defined  on the call back so the .txt is undefined
 scenario 2, it printed a gnuplot node list, without any generated data file to plot,  
 for scenario 4, apart from the user.txt file generated,  the output of the ./waf run,  gave a number (5.7077e+07 ) that was not also defined, its that the SINR value?   thank you sir for your response

**Comment by tommasozugno** [comment]
> scenario 1 generated sinr-mcs.txt was not defined on the call back so the .txt is undefined

The file sinr-mcs.txt is generated by the tracing function defined [here](https://github.com/signetlabdei/millicar/blob/eb1d8bb807718815441f7c1d6dea9336b0b5dcf9/helper/mmwave-vehicular-traces-helper.cc#L56), the different fields are described [here](https://github.com/signetlabdei/millicar/blob/eb1d8bb807718815441f7c1d6dea9336b0b5dcf9/helper/mmwave-vehicular-traces-helper.h#L51). 

> scenario 2, it printed a gnuplot node list, without any generated data file to plot,
The gnuplot script is generated by [this function](https://github.com/signetlabdei/millicar/blob/eb1d8bb807718815441f7c1d6dea9336b0b5dcf9/examples/vehicular-simple-two.cc#L179) and represents the position of the vehicles in the scenario, you can plot with the following gnuplot commands:
 ```
load 'scenario.txt'
plot 1/0 
``` 

> for scenario 4, apart from the user.txt file generated, the output of the ./waf run, gave a number (5.7077e+07 ) that was not also defined, its that the SINR value? thank you sir for your response

I think that value is printed by [this line](https://github.com/signetlabdei/millicar/blob/eb1d8bb807718815441f7c1d6dea9336b0b5dcf9/examples/vehicular-simple-four.cc#L146), it was added for debugging purposes and we forgot to remove it, I will fix it asap.

**Comment by obifranky** [comment]
Sir, i have checked the scenario 2 codes, apart from the vehicle movement
gnuplot file that was generated, it did not generate any other file, so in
such case how do i check the delay, SINR, and throughput. thank you
