### ISSUE TITLE
millicar scenario 2 and 4 performance evaluation for NLOS

### ISSUE THREAD

**Issue by obifranky** [signetlabdei/millicar#5]
the scenario 2 and 4 of the millcar, the .txt file generated was a gnuplotnodelistfile, please how can i get the delay, SINR and throughput since no data was generated.
for scenario 4, the ns3 ./waf run program printed a number  (5.7077e+07) with no definition. i have check the call back definition on the code, but it is not there. i am trying to compute the SINR for scenario 4. for NLOS
please sir i will appreciate your feedback. thank you

**Comment by tommasozugno** [comment]
I have already replied here: https://github.com/signetlabdei/millicar/issues/4

**Comment by obifranky** [comment]
there was no .txt generated for scenario 2, for delay or SINR, it only printed the gnuplot of the vehicle position
