### ISSUE TITLE
evaluation of scenario 2 

### ISSUE THREAD

**Issue by obifranky** [signetlabdei/millicar#6]
greetings
scenario 2 printed only the .txt gnuplot file of the vehicles movement, it did not generate file that shows the delay, or SINR , throughput. please how can i insert that into the program, i got error trying to see if i could generate the SINR file.
i also want to generate the SINR for scenario 4

thank you sir for your replies so far

**Comment by MatteoDrago** [comment]
Answer in #4 and #8
